version: "3.7"
services:
    db: #storage
       container_name: Invoice-db
       build:
           context: ./postgres
       environment:
           POSTGRES_PASSWORD: postgres
           POSTGRES_USER: postgres
           POSTGRES_DB: mydb
       volumes:
           - ./postgres/pgdata:/var/lib/postgresql/data
    
    web-backend: #backend
        container_name: Invoice-backend
        build:
            context: ./InvoiceLedger-backend
        ports:
            - "5000:5000"
        depends_on:
            - "db"
        environment:
            DB_HOST: db
        command: ["./wait-for-it.sh", "db:5432", "--", "node", "server.js"]
    web-frontend: #frontend
        container_name: Invoice-frontend
        build:
            context: ./Invoice-Ledger-FrontEnd
        ports:
            - "8080:80"
        depends_on:
            - "web-backend"
